#if UNITY_EDITOR
using Dan.Manager;
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;

public class SaveSceneHandler : UnityEditor.AssetModificationProcessor
{
    /// <summary>
    /// Handle when the scene is saved
    /// </summary>
    /// <param name="paths"></param>
    /// <returns></returns>
    public static string[] OnWillSaveAssets(string[] paths)
    {
        Debug.Log("Handle save asset");
        if(paths.Length == 1 && paths[0].EndsWith(".prefab"))
        {
            Debug.Log("Abord disabling script because it's a prefab save");
            return paths;
        }
        var sceneScript = GameObject.FindObjectOfType<SceneScriptBehaviour>();
        if(sceneScript == null)
        {
            sceneScript = CreateSceneScript();
        }
        sceneScript.GetAllScriptAndDisabled();

        foreach (string path in paths)
            Debug.Log(path);
        //Update the library file
        ScriptableObjectManager.UpdateLibrary();
        return paths;
    }

    /// <summary>
    /// Create the scene script gameobject
    /// </summary>
    /// <returns></returns>
    private static SceneScriptBehaviour CreateSceneScript()
    {
        Debug.Log("Create the scene script behaviour");
        var newGameObject = new GameObject("SceneScriptAutoGenerated",typeof(SceneScriptBehaviour));
        return newGameObject.GetComponent<SceneScriptBehaviour>();
    }
}
#endif